// <auto-generated />
using System;
using Masroof.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masroof.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MasroofDbContext))]
    [Migration("20261009094131_AddBnplCategory")]
    partial class AddBnplCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masroof.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("BankCode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IbanTail")
                        .HasColumnType("char(4)");

                    b.Property<bool>("IsOwn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Last4")
                        .HasColumnType("char(4)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId", "BankCode", "Last4")
                        .IsUnique()
                        .HasDatabaseName("UQ_Accounts")
                        .HasFilter("[BankCode] IS NOT NULL AND [Last4] IS NOT NULL");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Masroof.Domain.Entities.Category", b =>
                {
                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Color")
                        .HasColumnType("char(7)");

                    b.Property<bool>("ExcludeFromTotals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = (short)1,
                            Code = "groceries",
                            Color = "#4CAF50",
                            ExcludeFromTotals = false,
                            Icon = "shopping_cart",
                            NameAr = "بقالة",
                            NameEn = "Groceries"
                        },
                        new
                        {
                            CategoryId = (short)2,
                            Code = "dining",
                            Color = "#FF7043",
                            ExcludeFromTotals = false,
                            Icon = "restaurant",
                            NameAr = "مطاعم",
                            NameEn = "Dining"
                        },
                        new
                        {
                            CategoryId = (short)3,
                            Code = "transport",
                            Color = "#5C6BC0",
                            ExcludeFromTotals = false,
                            Icon = "directions_bus",
                            NameAr = "مواصلات",
                            NameEn = "Transport"
                        },
                        new
                        {
                            CategoryId = (short)4,
                            Code = "fuel",
                            Color = "#8D6E63",
                            ExcludeFromTotals = false,
                            Icon = "local_gas_station",
                            NameAr = "وقود",
                            NameEn = "Fuel"
                        },
                        new
                        {
                            CategoryId = (short)5,
                            Code = "utilities",
                            Color = "#FBC02D",
                            ExcludeFromTotals = false,
                            Icon = "bolt",
                            NameAr = "خدمات",
                            NameEn = "Utilities"
                        },
                        new
                        {
                            CategoryId = (short)6,
                            Code = "telecom",
                            Color = "#26A69A",
                            ExcludeFromTotals = false,
                            Icon = "sim_card",
                            NameAr = "اتصالات",
                            NameEn = "Telecom"
                        },
                        new
                        {
                            CategoryId = (short)7,
                            Code = "rent",
                            Color = "#7E57C2",
                            ExcludeFromTotals = false,
                            Icon = "home",
                            NameAr = "إيجار",
                            NameEn = "Rent"
                        },
                        new
                        {
                            CategoryId = (short)8,
                            Code = "health",
                            Color = "#EF5350",
                            ExcludeFromTotals = false,
                            Icon = "local_hospital",
                            NameAr = "صحة",
                            NameEn = "Health"
                        },
                        new
                        {
                            CategoryId = (short)9,
                            Code = "education",
                            Color = "#42A5F5",
                            ExcludeFromTotals = false,
                            Icon = "school",
                            NameAr = "تعليم",
                            NameEn = "Education"
                        },
                        new
                        {
                            CategoryId = (short)10,
                            Code = "shopping",
                            Color = "#EC407A",
                            ExcludeFromTotals = false,
                            Icon = "shopping_bag",
                            NameAr = "تسوق",
                            NameEn = "Shopping"
                        },
                        new
                        {
                            CategoryId = (short)11,
                            Code = "entertainment",
                            Color = "#AB47BC",
                            ExcludeFromTotals = false,
                            Icon = "movie",
                            NameAr = "ترفيه",
                            NameEn = "Entertainment"
                        },
                        new
                        {
                            CategoryId = (short)12,
                            Code = "travel",
                            Color = "#29B6F6",
                            ExcludeFromTotals = false,
                            Icon = "flight",
                            NameAr = "سفر",
                            NameEn = "Travel"
                        },
                        new
                        {
                            CategoryId = (short)13,
                            Code = "family_transfer",
                            Color = "#66BB6A",
                            ExcludeFromTotals = false,
                            Icon = "family_restroom",
                            NameAr = "تحويل عائلي",
                            NameEn = "Family Transfer"
                        },
                        new
                        {
                            CategoryId = (short)14,
                            Code = "salary",
                            Color = "#9CCC65",
                            ExcludeFromTotals = false,
                            Icon = "payments",
                            NameAr = "راتب",
                            NameEn = "Salary"
                        },
                        new
                        {
                            CategoryId = (short)15,
                            Code = "refund",
                            Color = "#26C6DA",
                            ExcludeFromTotals = false,
                            Icon = "undo",
                            NameAr = "استرداد",
                            NameEn = "Refund"
                        },
                        new
                        {
                            CategoryId = (short)16,
                            Code = "fees_charges",
                            Color = "#BDBDBD",
                            ExcludeFromTotals = false,
                            Icon = "receipt_long",
                            NameAr = "رسوم",
                            NameEn = "Fees & Charges"
                        },
                        new
                        {
                            CategoryId = (short)17,
                            Code = "atm_cash",
                            Color = "#78909C",
                            ExcludeFromTotals = false,
                            Icon = "local_atm",
                            NameAr = "صراف / نقد",
                            NameEn = "ATM / Cash"
                        },
                        new
                        {
                            CategoryId = (short)18,
                            Code = "investment",
                            Color = "#2E7D32",
                            ExcludeFromTotals = false,
                            Icon = "trending_up",
                            NameAr = "استثمار",
                            NameEn = "Investment"
                        },
                        new
                        {
                            CategoryId = (short)19,
                            Code = "government",
                            Color = "#546E7A",
                            ExcludeFromTotals = false,
                            Icon = "account_balance",
                            NameAr = "حكومي",
                            NameEn = "Government"
                        },
                        new
                        {
                            CategoryId = (short)20,
                            Code = "other",
                            Color = "#90A4AE",
                            ExcludeFromTotals = false,
                            Icon = "category",
                            NameAr = "أخرى",
                            NameEn = "Other"
                        },
                        new
                        {
                            CategoryId = (short)21,
                            Code = "transfer_internal",
                            Color = "#78909C",
                            ExcludeFromTotals = true,
                            Icon = "swap_horiz",
                            NameAr = "تحويل داخلي",
                            NameEn = "Internal Transfer"
                        },
                        new
                        {
                            CategoryId = (short)22,
                            Code = "bnpl",
                            Color = "#9575CD",
                            ExcludeFromTotals = false,
                            Icon = "schedule",
                            NameAr = "اشترِ الآن وادفع لاحقًا",
                            NameEn = "Buy Now Pay Later"
                        });
                });

            modelBuilder.Entity("Masroof.Domain.Entities.Feedback", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FeedbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("FeedbackId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Masroof.Domain.Entities.MerchantRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("varchar(80)");

                    b.Property<int>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RuleText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SubjectNorm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RuleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "SubjectNorm")
                        .IsUnique()
                        .HasDatabaseName("UQ_Rule");

                    b.ToTable("MerchantRules", (string)null);
                });

            modelBuilder.Entity("Masroof.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OutboxId"));

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("OutboxId");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_Outbox_Unprocessed");

                    b.ToTable("Outbox", (string)null);
                });

            modelBuilder.Entity("Masroof.Domain.Entities.ParseTrace", b =>
                {
                    b.Property<long>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TraceId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HintsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RawOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("TraceId");

                    b.HasIndex("TransactionId");

                    b.ToTable("ParseTraces", (string)null);
                });

            modelBuilder.Entity("Masroof.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Channel")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(4,3)");

                    b.Property<string>("Counterparty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CounterpartyNorm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<bool>("IsCorrected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RawTextHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<Guid?>("TransferGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TxnDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "RawTextHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_Txn_Dedupe");

                    b.HasIndex("UserId", "TransferGroupId")
                        .HasDatabaseName("IX_Txn_TransferGroup");

                    b.HasIndex("UserId", "TxnDate")
                        .HasDatabaseName("IX_Txn_User_Date");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "TxnDate"), new[] { "Amount", "Direction", "CategoryId" });

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Txn_Amount", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Txn_Direction", "[Direction] IN ('debit','credit')");
                        });
                });

            modelBuilder.Entity("Masroof.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("SAR");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("en");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Masroof.Domain.Entities.Account", b =>
                {
                    b.HasOne("Masroof.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Masroof.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Masroof.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Feedback")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Masroof.Domain.Entities.MerchantRule", b =>
                {
                    b.HasOne("Masroof.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Masroof.Domain.Entities.User", "User")
                        .WithMany("Rules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Masroof.Domain.Entities.ParseTrace", b =>
                {
                    b.HasOne("Masroof.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Traces")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Masroof.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Masroof.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Masroof.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Masroof.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Masroof.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Traces");
                });

            modelBuilder.Entity("Masroof.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Rules");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
