<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Masroof.Worker-5dc3abab-0145-4785-81d3-417fe035bbba</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Masroof.Application\Masroof.Application.csproj" />
    <ProjectReference Include="..\Masroof.Infrastructure\Masroof.Infrastructure.csproj" />
    <ProjectReference Include="..\Masroof.Domain\Masroof.Domain.csproj" />
  </ItemGroup>
</Project>
